### ISSUE TITLE
DrawLine should use Vector3 as well

### ISSUE THREAD

**Issue by KornelGM** [eppz/Unity.Library.eppz.Lines#1]
Hi,

`DrawLine` uses `Vector2` and because of this it does not work for me (I tried to visualize `AddForce`). Changing both parameters to `Vector3` fixed the issue.

**Comment by Geri-Borbas** [comment]
Yap, thanks for pointing out. I made this mainly to debug [**eppz! Geometry**](https://github.com/eppz/Unity.Library.eppz.Geometry), so it is mostly 2D. Still, there are methods where `z` coordinate is omitted, see drawing methods in [`LineRendererBase#Drawing methods`](https://github.com/eppz/Unity.Library.eppz.Lines/blob/master/LineRendererBase.cs#L59).

You may create a PR with the changes, so I could merge the changes.

**Comment by KornelGM** [comment]
Done :)

**Comment by Geri-Borbas** [comment]
Thanks. Just merged! 🎉
